import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar/navbar'
import Cursor from './components/Cursor/cursor'
import Grain from './components/grain'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'James Nguyen ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>          
        <Cursor></Cursor>
        <Grain></Grain>
        {/* <Navbar className='flex fixed bottom-8 justify-center w-screen'></Navbar> */}
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}
